.gitignore
config.h.in
configure.ac
src/Makefile.am
src/compat/strlcat.c
src/compat/strlcat.h
src/compat/strlcpy.c
src/compat/strlcpy.h
src/io.c
src/ui.c

Should fix https://github.com/thoughtbot/pick/issues/6
**Needs to be tested on bsd**

Define our own strlcpy if one doesn't exist

---

DEVELOPING.md

While contributing to this project I had a lot of trouble getting vim
setup correctly. Whether or not we check this in I think we should
provide these settings to other developers so they don't have issues
with indentation and such.

Add project specific vimrc

---

man/man1/pick.1
src/main.c

Detect running from within Vim and automatically disable usage of the
alternate screen.

Automatically disable alternate screen in Vim.

---

src/ui.c

When feeding pick a lot of choices (> 100,000), typing fast on the keyboard
while entering the search query could make pick drop input characters.
By using separate input and output streams rather than one stream for both,
we avoid this issue.
Closes #45

Use separate input and output streams

---

src/Makefile.am
src/choice.c
src/choice.h
src/choices.c
src/choices.h
src/io.c
src/io.h
src/main.c
src/tty.c
src/tty.h
src/ui.c
src/ui.h

Refactorings to improve readability, extensibility and error handling.
More refactorings will follow. In particular, I'd like to clean up the massive case statement in `ui.c` and the crazy nested for loops in `min_match_length` in `choices.c`. That's for the next PR, though.

Refactorings

---

README.md

Add Debian/Ubuntu installation instructions

---

src/main.c

Remove duplication in `selected_choice` by merging switch cases with the
same body.

Remove duplication in `selected_choice`

---

src/main.c

Use the `CTRL` macro in `sys/ttydefaults.h`

---

src/main.c

- Inline one line functions which names are not needed for clarification
of their functionality.
- Simplify initialization in `selected_choice`.

Refactor and reformat for clarity

---

src/main.c

Previously when a query that wouldn't fit within the number of columns
of the tty was entered, the query input field would be unable to show
the full query.
This commit adds horizontal scrolling to the query input field. When the
cursor is moved outside of the currently visible part of the query, the
query is scrolled to show the previously invisible part.

Scroll query horizontally as needed

---

src/main.c

Simplify `min_match_length` by replacing the existing iterative
algorithm with a recursive one.

Simplify `min_match_length`

---

src/pick.c

When counting how many characters are left to print from the end of a
choice to the right-most column of the tty, disregard escape sequences.
This fixes #100.

Only count printable characters

---

src/pick.c

Since the number of recognized keys is limited make the `get_key'
function return a integer constant representing the read key. This
removes the need to cast the key buffer to an integer which broke strict
aliasing.

Change get_key to return the read key

---

tests/test.c

Avoid EIO while testing on linux

---

tests/test.c

The input was being written prior the tcsetattr call in the pick
process which caused line editing to alter the input.
While at it: sort variables by size according to style(9).
Partial solution to #116.

Fix tcsetattr timing issue

---

man/man1/pick.1

Document the behavior of Ctrl-C

---

src/pick.c

- make function get_key() work on big endian machines

change keycode structure in get_key()

---

tests/pick-test.c

I decide it was worth trying to fix this potential overflow. Thoughts?

Fix potential integer overflow

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md

@mptre and @mike-burns, what do you think about the updated code of conduct?
Would you like to receive email for the <pick-maintainers@calleerlandsson.com> alias?

Update and include the project's code of conduct

---

pick.1

As discussed in https://github.com/calleerlandsson/pick/commit/db10ff312c514276c5767bf8c2337f0f16e29515.

Move thoughtbot to HISTORY

---

Makefile.am
pick.c
tests/44.t
tests/45.t

Recognize carriage return as enter

---

pick.c

This is a hot path and it looks more like a left-over from a previous
design.

Inline score function

---

tests/pick-test.c

Instead of doing [this][homebrew], `pick-test(1)` should setup the environment
needed by `pick(1)`.
Once the released the referenced line could be removed from the homebrew
recipe.
Thoughts @calleerlandsson and @teoljungberg?
[homebrew]: https://github.com/Homebrew/homebrew-core/blob/master/Formula/pick.rb#L15

Setup crucial environment for pick in pick-test

---

.travis.yml

Allows us to spot errors in the manual more easily. Looks good?

Run mandoc on Travis

---

Makefile.am
pick.1
pick.c
tests/03.t
tests/47.t
tests/48.t

Now in sync with the latest upstream and fixing some minor bugs ...
Thanks for the kind words and the patience while I'm messing with "git rebase" ... ;-)

Add Keys for End/Home and Ctrl-H for Backspace

---

compat.h
tests/pick-test.c

Declare dead functions

---

Makefile.am
pick.1
pick.c
tests/13.t
tests/59.t
tests/60.t

This is equivalent to the ALTWERASE algorithm.
Based on previous work done by Jenz Guenther in PR #231 but further
enhanced to support UTF-8.

Recognize alphanumeric and underscore characters as words

---

pick.c

Simplify the prototype by only passing a pointer-pointer that will point
to the input buffer upon return.
While here, declare the buffer as unsigned since the signedness of char
can differ between platforms. This issue was also pointed out by Jenz
Guenther in PR #217.

Refactor get_key()

---

pick.c

An abstraction worth performing since we can unify the internal state
reset and there's currently no need to distinguish between the two
scenarios where mbtowc() returns -1 or 0.

Unify mbtowc() invocation and error handling

---

pick.c

- Since we can have SIZE_T_MAX many choices, don't use plain signed
integers.
- Make `choices_lines` unsigned to keep it consistent with
`tty_{columns,lines}` since commit b5fe77f ("Make tty_{columns,lines}
unsigned").
- Drop (by now) redundant casts to size_t
- Rework some logic in order to prevent doing subtraction on unsigned
integers since it could result in wrapping.
- Rework the complex loop in print_choices() by keeping the upper bound
in the loop declaration. The other loop condition is better suited
inside the body of the loop. This convention is in general a good rule
of thumb while constructing complex loops.
Testing would be much appreciated! Especially `Page-{Down,Up}`.

Consistently use size_t while counting choices

---

pick.c

Some key bindings only affect the query and unconditionally redrawing
the choices is therefore a wast of time in such scenarios.
Originally proposed by Jenz Guenther in PR #254.

Only redraw the choices when necessary

---

Makefile
configure

Should solve the issues mentioned in #292.

GNU compat

---

.gitignore

This keeps the git workspace clean after builds

Add *.o *.d and pick to .gitignore file
