mptre/pick

man/man1/pick.1, src/main.c, src/ui.c, src/ui.h
- Replace ncurses with tputs and termios.
- Add an `-X` option to disable use of the alternate screen.
Hopefully solves #4, #18, #19 and #20.
@Keithbsmiley, @mike-burns, @teoljungberg  and @ggilder, could you guys help test this on your machines?
=> Solve Vim `system()` related issues.

README.md
After fixing the issues related to Vim `system()` I feel confident removing
the notice about pick being experimental software.
=> Remove experimental notice.

Makefile.am
The sha of the tarball generated by `make distcheck` is different on every
run because of the file modification time of files in the archive.
Downloading the actual release tarball and using the sha for that in the
Homebrew formula and AUR PKGBUILD ensures that they contain the correct sha.
=> Use the sha of the actual release tarball.

src/ui.c
This avoids illegal seek errors when users send input while we're
outputting to the terminal.
Closes #42.
=> Open `/dev/tty/` in read and append mode. 

src/choices.c
Choices with the same score would be sorted randomly creating an
nondeterministic ordering which confused users.
Choices will now be sorted lexicographically within the same score.
Closes #50
=> Sort choices lexicographically

README.md
pick is now on MacPorts (https://trac.macports.org/browser/trunk/dports/devel/pick/Portfile).
=> Add installing via MacPorts instruction

config.h.in, configure.ac, src/Makefile.am, src/compat/reallocarray.c, src/compat/reallocarray.h, src/ui.c
When reallocating memory using `realloc`, passing in a number produced by a
multiplication operation, there is a risk of multiplication overflow:
realloc(str, len * sizeof(char))`
These overflow issues can be avoided by using `reallocarray`.
`reallocarray` is implemented in the OpenBSD libc and has been added to
`compat/` for portability.
Closes #59.
=> Prefer `reallocarray` over `realloc`

src/ui.c
When displaying as many or more results than the number of lines in the
terminal, when the last result's length was longer than the width of the
terminal, the extra characters would push the first result up into the
input field.
By not printing more characters than would fit the terminal width, this
behavior is avoided.
=> Prevent scrolling

src/main.c
When tty_putp fails the following message is outputted:
```
pick: tputs: Success
````
Since tputs does not set errno this message is confusing. Instead output
the name of the missing capability:
````
pick: enter_ca_mode: unknown terminfo capability
````
Notice that enter_ca_mode is just an example and will be substituted with
the capability that caused the failure during execution.
Discovered using pick with the Linux console.
=> Improve tty_putp error message

src/main.c
Pressing Ctrl-K should (according to the man page) delete until the end
of the line. Previously, it would not delete the character under the
cursor and when pressed twice it would bring back the deleted characters
or segfault, depending on the system, due to a memory access error.
This commit fixes the memory access bug and brings the behavior in line
with Bash and Readline which both deletes the character under the
cursor.
=> Fix Ctrl-K

src/pick.c
My assumption was wrong in this case.
Can be verified:
```bash
printf 'a\nb\n' | LINES=2 pick
```
Prior this change an empty lines was emitted.
=> Fix off-by-one bug

src/pick.c
With acd349122e36a49e17e3c04a54cfb08bea9e50fd the CTRL macro started
being used but <sys/ttydefaults.h> was never explicitly included, which
broke the build when using the Android NDK or the musl libc.
=> Include <sys/ttydefaults.h> for the CTRL macro

src/pick.c, tests/09.in, tests/10.in, tests/11.in, tests/12.in, tests/13.in, tests/14.in, tests/15.in, tests/16.in, tests/17.in, tests/test.c
Work in progress, would really appreciate some help with testing. A few notes in no particular order:
- The `get_key` function recognizes both `\033[` and `\033O`, which terminal omits the later?
- I changed `BACKSPACE` from `263` to `8` which is the decimal number for the backspace character. Is this a bad idea? Where did `263` come from?
- Comparing Unicode characters is not case insensitive. Using one of the wide character comparision functions seems to best way to do it at glance since it's not as trivial as comparing ASCII characters. Input on this would be appreciated.
=> Add Unicode support

src/pick.c
Emitting the `clr_eos` capability will clear all columns from the
current cursor position (inclusive) to the end of the screen. If the
last line was selected the last column would therefor also be cleared
including the standout. The solution is simply to clear the screen prior
redrawing the interface.
=> Fix standout rendering of last line

src/pick.c
Regression from e79f95b. ESCAPE is not a recognized key but instead used
in the `count_printable` function in order to recognize a escape
character.
=> Revert unintentional escape macro change

tests/test.c
Enable malloc.conf(5) options on OpenBSD which will abort the pick process when
reading/writing out-of-bounds or accessing already freed memory. A core-file is
created on failure and can be inspected using gdb(1):
```
gdb -c pick.core src/pick
```
=> Run tests with MALLOC_OPTIONS=S OpenBSD

README.md
* Change from 2015 to 2016.
* Link to thoughtbot Stockholm page, open source page, hire us page.
* Add thoughtbot logo.
=> Update copyright, add thoughtbot details

README.md
I maintain the package for pick on FreeBSD, and wanted to add the sections to README.md about installing pick.
=> Add sections for installing pick on FreeBSD

src/pick.c
An attempt to solve #131 turned into a bigger change than expected, for better IMHO. See each commit messages for more info. Would really like to get feedback from all of you.
=> Refactor print logic

config.h.in, configure.ac, src/pick.c, tests/20.in, tests/21.in, tests/test.sh
Minor changes this time. Let me know what you think.
=> Cleanup and missing tests

Makefile.am, tests/36.t, tests/37.t, tests/38.t, tests/39.t, tests/40.t, tests/41.t, tests/42.t, tests/README.md, tests/test.sh
Using `gcov(1)` revealed a couple of code paths not covered by the
tests. Some of the uncovered behavior can't be verified using the
current test framework but a potential crash can still be detected.
=> Improve test code coverage

src/pick.c
From `style(9)`:
> Right-justify the backslashes, as the resulting definition is easier to
> read.
=> Right-justify backslashes according to style(9)

Makefile.am, src/pick.c, tests/43.t
If the user inputs a unrecognized escape sequence longer than the size
of the input buffer, parts of the sequence would end up in the query.
Since the sequence should be ignored, there's no need to put the read
bytes in the input buffer.
=> Discard unrecognized escape sequences

src/pick.c
Usage of cursor save and restore capabilities is non-obvious. Moving the
cursor the appropriate number of lines/columns is easier to follow.
While at it, make the query cursor movement a single operation as
opposed of the current implementation which is linear with the number of
characters in the query.
I would appreciate if others could test this change in order to not
introduce any regression.
=> Remove usage of save and restore cursor

.gitignore, Makefile.am, tests/pick-test.c
Preparing for release, I ran `make distcheck` and found it failing. With the changes in this PR it is passing.
@mptre, I'd love your feedback on the changes and also if you could try running it on your system.
=> Make `make distcheck` pass

src/pick.c
Changes to `min_match`, `strcasechr` and UTF-8 functions.
=> Refactoring and cleanup

.travis.yml
In addition to running the test suite (just like the `check` Make
target), the `distcheck` target also takes the following steps to test
the distribution:
- tries to do a `VPATH` build, with the `srcdir` and all its content
made read-only;
- installs the package in a temporary directory (with `make install`),
and tries runs the test suite on the resulting installation (with
`make installcheck`);
- checks that the package can be correctly uninstalled (by `make
uninstall`) and cleaned (by `make distclean`);
- finally, makes another tarball to ensure the distribution is
self-contained.
For more info, see https://www.gnu.org/software/automake/manual/html_node/Checking-the-Distribution.html
=> Run distcheck in favor of check on Travis CI

configure.ac
I've always found it odd that pick favors linking against ncursesw if
present instead of curses. This gets even more interesting on my machine
where the ncursesw library is present but not the headers. This means in
practice: the curses headers are used but later linked against ncursesw.
However, it does work since ncursesw implements the same API as curses.
My proposal is to make linking against ncursesw a opt-in feature since
the more common curses library should be favored if available.
This patch adds a `--{with,without}-ncursesw` option to the configure
command, which defaults to false. The change is therefore breaking in
sense that users with only ncursesw available has to pass the new option
while running configure. A reasonable compromise in my opinion since
less implicit …
=> Make linking against ncursesw opt-in

DEVELOPING.md, configure.ac
This prevents me from becoming a bottleneck in communications.
@mptre, @mike-burns: if you think the maintainers email idea mentioned in #170 is good, maybe this could also be an improvement?
=> Use a non-personal email for the project

pick.1
- Less verbose by reducing the usage of Nm
- Mention stdin/stdout for input/output
- Sort options, disregarding case
- Turn option descriptions into sentences
- Update cross-reference: ncurses -> curses
- Move keys into commands section, inspired by less(1)
- Simplify examples using Dl and add prefix with shell prompt, de facto
standard to emphasis on the privileges needed to run the command
- Add diagnostics section
- Remove redundant quotes around authors and turn emails into hyperlinks
=> Cleanup man page

config.h.in, configure.ac
Validating existence of things that hasn't changed since the 80s seems
wasteful. Especially when the types, headers and functions to look for
is out-of-date in respect to what's used by pick.
Looking for the two non-portable functions pledge and reallocarray makes
sense and is therefore kept as is.
=> Remove unused autoconf checks

pick.c
If the end of the match is greater than the number of columns the
underline attribute will spill over on the next line since it's never
exited. Running the following command before/after applying this commit
highlights the bug:
```sh
for _ in 0 1; do
jot -n -s '' $(($COLUMNS - 1)) 0 0
echo ab
done | pick -q ab
```
=> Fix underline spill over bug

compat.h
I propose we only define `__dead` to the empty string if it's missing
since the current `ifdef`-logic is rather complex and we don't want to
maintain support for all various platforms and compilers.
=> Only define __dead if it's missing

DEVELOPING.md, README.md
I haven't been running Arch Linux for a while now. Therefor, maintaining the Arch package has been a bit of a hassle to the extent of it falling behind a version.
If someone wants to to take over maintaining the package I would appreciate it a lot and transfer ownership of the AUR package. If not, I'll disown the package on the AUR site and someone else can pick it up in the future.
Let's let this PR sit for at least a week before merging.
=> Stop maintaining the Arch Linux package

pick.c, tests/06.t, tests/19.t
A recent discussion on the OpenBSD [tech-mailing-list] brought to my
attention that sysexits.h originates from sendmail(8) and further usage
is not encouraged.
Ping @calleerlandsson @mike-burns 
[tech-mailing-list]: http://marc.info/?l=openbsd-tech&m=149191614721371&w=2
=> Remove usage of sysexits.h

Makefile.am, pick.c
In an attempt to fix #184 caused by lines including Unicode characters
that occupy more than one column.
While at it, fix another bug related to the column counter when a line
contains more than one escape sequence.
Reviews and testing would be much appreciated I haven't discovered any
regression nor performance decrease running this diff so far.
/cc @calleerlandsson @mike-burns @teoljungberg.
=> Calculate the width of each displayed character

pick.c
Increment the column counter prior decrementing the calculated width of
the tab.
Regression introduced in commit 369350b (Calculate the width of each
displayed character).
Sorry, can we do a patch release @calleerlandsson?
=> Fix tab output bug

pick.c
I had this diff laying around, finally took the time to split it up into several
commits. Thoughts and feedback are much appreciated.
=> Refactor get_key

pick.c
Instead of explicitly list all key bindings that could be either CR or
NL, make use of the ICRNL input mode.
@teoljungberg could you verify that this PR work as intented on your setup?
=> Map CR to NL

pick.c
In an attempt to fix #98 and #196.
=> Don't move the cursor upwards if no choices where printed

pick.c
Some implementations like NetBSD have a non-variadic prototype of
tparm() requiring 9 explicit parameters. Therefore always make sure to
pass 9 parameters. Since other implementations uses a variadic prototype
it will work on them as well.
Inspired by how this solved in the portable version of tmux.
=> Always pass 9 parameters to tparm()

pick.c
Also, prefix DOWN for consistency.
Issue reported by Jenz Guenther in PR #216.
=> Prefix UP since it's already defined on NetBSD

Makefile.am, pick.c, tests/58.t
Just discovered a severe bug in the matching algorithm, please give it a
try:
> Instead of unconditionally returning the length of the current match,
> make sure the shortest match bubbles up along the recursive call stack.
> 
> Note that this bug only occurs when a choice contains multiple instances
> of the query and the right-most match is the shortest one. See the
> example below including the choice, query, match prior this commit and
> after:
> 
> ```
> Choice       Query  Before       After
> aa/åå/aa/aa  aa/aa  aa/åå/aa/aa  aa/åå/aa/aa
> 		    ^      ^           ^   ^
> 		    |------|           |---|
> ```
=> Favor the shortest match

Makefile.am, pick.1, pick.c, tests/64.t
The current SIGINT handler is not considered safe since it invokes
functions that are not considered asynchronous safe[1]. Quoting the
CERT C Coding Standard:
In general, it is not safe to invoke I/O functions from within signal
handlers.
Instead, do not turn control characters into signal but instead handle
the relevant ones explicitly. A pleasant side-effect is being able to
test the Ctrl-C error path.
While here, fix the broken suspend/resume behavior by resetting the
initial terminal state prior suspending and re-read it upon resume. I do
actually use suspend/resume while running pick when I forgot to check
something that will affect the choice to select.
[1] https://www.securecoding.cert.org/confluence/display/c/SIG30-C.+Call+only+asynchronous-safe+functions+within+signal+handlers
=> Explicitly handle control characters

pick.1, pick.c
Useful when running pick from within another interactive program (like
vim(1)) which does not re-enable keyboard transmit mode after executing
an external program.
Fixes #246.
=> Add K option to disable toggling of keyboard transmit mode

pick.c
Makes pick compile using musl-libc, reported by Michael Gehring in #249.
=> Inline CCEQ macro

Makefile.am, pick.c, tests/46.t, tests/68.t
It was brought to my attention that pick didn't handle OSC escape
sequences correctly. Make sure to ignore them while calculating the line
width for each choice and ignore them while matching.
=> Ignore OSC escape sequences

pick.c
If the user didn't add more characters to the query all choices have to
be reconsidered as potential matches. In the opposite scenario, there's
no point in reconsidered all choices again since the ones that didn't
match the previous query will clearly not match the current one due to
the fact that previous query is a left-most substring of the current
one.
Testing would be much appreciated. On large inputs, pick should feel
snappier by now.
=> Low-hanging optimization

Makefile.am, pick.1, pick.c, tests/key-ctrl-o.t
I use pick to find Git commits, a lot. I generally make use of the `-S`
option since newer commits (lines near the beginning of input) is often
more relevant than older ones with a higher score. However, it would be
convenient to be able to toggle sorting on and off.
Unfortunately, this binding conflicts with [STOP](http://man.openbsd.org/termios#VSTOP), might not be a problem
but proposals on a different binding are welcome.
=> Add toggle sorting key binding

pick.c
Typing a query fast enough to trigger the poll check in filter_choices()
could yield a wrong set of choices. Since filter_choices() is
interrupted, all choices have yet not been examined and potential
matches could still be left unexamined. Calling print_choices() in this
state causes the unexamined choices to never be reconsidered as
potential matches since they will have a score = 0. The solution is to
never call print_choices() if filter_choices() was interrupted.
Problem reported and partial solution provided by Jenz Guenther in
GitHub issue #268.
=> Ensure correctness while typing a query fast

.travis.yml, Makefile.am
It's generally considered bad practice to ship software with this flag.
Issue revealed while updating the port on [OpenBSD].
[OpenBSD]: https://marc.info/?l=openbsd-ports&m=151482370923381&w=2
=> Remove Werror compiler flag

README.md
- Merge the initial paragraph with usage, now that we can refer to manual
- Limitations of calling pick from within Vim is better of described in the
README of pick.vim
/cc @calleerlandsson @teoljungberg @mike-burns
=> Trim down README

tests/pick-test.c
Fixes #281.
@DBOTW or @giappi could you please verify that this works as intended on Arch Linux?
=> Favor LC_ALL over LC_CTYPE in pick-test

Makefile, configure
Ran into some problems while trying to package for OpenBSD. Turns out it's a better idea to only honor `PREFIX` during configure and during install always use dedicated variables for paths.
Does this work for everyone else?
/cc @dbotw @eavgerinos
=> Honor BINDIR during configure and install

CONTRIBUTING.md
I will maintain packages for Fedora, RHEL, and CentOS.  Once RPMs are available I will update the README with instructions.
=> Add Ben Porter to package maintainers for RPM

pick.c
The kend capability is issued by some keypads while pressing enter in
cursor mode.
Fixes #308
=> add missing enter key mapping

README.md
RPMs are now built for Fedora 33, aarch64 and x86_64
Also remove reference to Fedora 30 which is now EOL
=> Update Fedora instructions for Fedora 33
